DROP TABLE   QuestProducts  ;
 CREATE TABLE   QuestProducts
   (
   productID   int   NOT NULL,
   ProductName    varchar(200)    NOT NULL,
   Description    varchar(600)    NOT NULL,
   ImageURL    varchar(600)    NOT NULL,
   DollarPrice  varchar(20)     NOT NULL,
   PRIMARY KEY ( productID )
   )
   CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO QuestProducts VALUES (1,'Acer Aspire Laptop','15.6" Full HD Widescreen Display','https://images-na.ssl-images-amazon.com/images/I/71Tl%2BD5RcNL._SL1500_.jpg','$799.99');
INSERT INTO QuestProducts VALUES (2,'Acer Aspire Notebook','15.6" Full HD Widescreen Display','https://images-na.ssl-images-amazon.com/images/I/61Yeir0uhIL._SL1322_.jpg','$349.99');
INSERT INTO QuestProducts VALUES (3,'ASUS Android Tablet','8" Touch Screen','https://images-na.ssl-images-amazon.com/images/I/41JYmgGBhRL.jpg','$126.00');
INSERT INTO QuestProducts VALUES (4,'Apple iPad','Processor: 1.65 GHz RAM: 128 GB (2017 Newest Model) (Certified Refurbished)','https://images-na.ssl-images-amazon.com/images/I/61fCSQw997L._SL1000_.jpg','$359.99');
INSERT INTO QuestProducts VALUES (5, 'Apple iPhone', '32GB - Rose Gold, 3D Touch (Certified Refurbished)','https://images-na.ssl-images-amazon.com/images/I/71x3e0x%2BM2L._SL1382_.jpg','$406.50');
INSERT INTO QuestProducts VALUES (6, 'Samson Galaxy Phone','Worlds first Infinity Screen 64 GB Unlocked International Version (Midnight Black)','https://images-na.ssl-images-amazon.com/images/I/61FgyIm6rLL._SL1383_.jpg','$627.78');
INSERT INTO QuestProducts VALUES (7, 'Android Smartphone Certified Preowned','4G LTE prepaid 32GB smartphone includes Wi-Fi, GPS and Bluetooth','https://images-na.ssl-images-amazon.com/images/I/81S6qfVnW-L._SL1500_.jpg','$47.95');
INSERT INTO QuestProducts VALUES (8, 'Jitterbug Flip Cell Phone','Big buttons, simple “Yes” and “No” navigation, a backlit keypad, camera, powerful speaker.','https://images-na.ssl-images-amazon.com/images/I/71ukSZ3p5fL._SL1500_.jpg','$60.76');
INSERT INTO QuestProducts VALUES (9,'HP OfficeJet Printer','Wireless All-in-One Photo Printer with Mobile Printing, Instant Ink ready.','https://images-na.ssl-images-amazon.com/images/I/71sDg%2By9t4L._SL1500_.jpg','$84.99');
INSERT INTO QuestProducts VALUES (10, 'Canon Laser Printer','Print, scan, copy and fax capabilities, speeds of up to 28 pages per minute.','https://images-na.ssl-images-amazon.com/images/I/51LsIu6zMPL._SY355_.jpg','$159.99');
INSERT INTO QuestProducts VALUES (11, 'Samsung HD Smart LED TV','65-Inch 4K Ultra HD Smart LED TV (2017 Model)','https://images-na.ssl-images-amazon.com/images/I/616%2BK6M825L._SL1000_.jpg','$879.00');
INSERT INTO QuestProducts VALUES (12, 'Sceptre LED HDTV, 40"','True Black (2017 Model), 1080P resolution, 3 HDMI ports.','https://images-na.ssl-images-amazon.com/images/I/71o6E6A4-1L._SL1080_.jpg','$229.95');
INSERT INTO QuestProducts VALUES (13, 'Bose Bluetooth Speaker','Full-range, portable sound, water-resistant speaker, up to 8 hours of music, rechargeable via Micro-B USB. ','https://images-na.ssl-images-amazon.com/images/I/614CIL31pML._SL1000_.jpg','$129.00');
INSERT INTO QuestProducts VALUES (14, 'Amazon Mini Speaker','Shockproof and Waterproof, Bluetooth, Wireless. ','https://images-na.ssl-images-amazon.com/images/I/814brDKfU9L._SL1500_.jpg','$21.59');
INSERT INTO QuestProducts VALUES (15, 'Floorstanding Loudspeaker','Ideal for home theater systems, uses three 5-1/4 inch woofers with oversized magnets for powerful bass.','https://images-na.ssl-images-amazon.com/images/I/61JSLgWnj1L._SL1000_.jpg','$198.00');
INSERT INTO QuestProducts VALUES (16, 'Floorstanding Loudspeaker','Ideal for home theater systems, uses three 5-1/4 inch woofers with oversized magnets for powerful bass.','https://images-na.ssl-images-amazon.com/images/I/71LjQpIzpdL._SL1500_.jpg','$18999.99');
INSERT INTO QuestProducts VALUES (17, 'Bose Wireless Headphones','Deep, immersive sound at any volume. Dual microphone system rejects noise and wind. Uses Bluetooth technology.','https://images-na.ssl-images-amazon.com/images/I/6188bLRU64L._SL1000_.jpg','$229.00');
INSERT INTO QuestProducts VALUES (18, 'Professional Monitor Headphones','Enhanced audio clarity and sound isolation. Designed primarily for studio tracking and mixing.','https://images-na.ssl-images-amazon.com/images/I/81APjlVpgbL._SL1500_.jpg','$68.00');
INSERT INTO QuestProducts VALUES (19, 'Sony Extra Bass Earbud Headset','Extra Bass Design, 12mm Drivers. Customized Android Control.','https://images-na.ssl-images-amazon.com/images/I/61p1oDWAPUL._SL1200_.jpg','$25.99');
INSERT INTO QuestProducts VALUES (20, 'Bluetooth Noise-Cancelling Headphones','Bluetooth headphones for running. Lightweight and comfortable. Inner nano-coating protects them from sweat and moisture. 9 hour battery life, fully recharged after only 2 hours. ','https://images-na.ssl-images-https://www.amazon.com/Headphones-TaoTronics-Sweatproof-Lightweight-Cancelling/dp/B074QKS8RK/ref=lp_12097478011_1_7?s=aht&ie=UTF8&qid=1519190124&sr=1-7amazon.com/images/I/51ru85hMQTL._SL1000_.jpg','$25.99');
INSERT INTO QuestProducts VALUES (21, 'Bananas, 1 bunch','One bunch contains approximately 5-7 bananas. Product is shipped right before it’s ready to eat but it may take up to one day to ripen. Color may vary from slightly green to yellow.','https://images-na.ssl-images-amazon.com/images/I/71gI-IUNUkL._SL1500_.jpg','$1.58');
INSERT INTO QuestProducts VALUES (22, 'Strawberries, 1 lb','AmazonFresh guarantees every product will be delivered to your home well within the manufacturers recommended use by, sell by, best by or expiration date.','https://images-na.ssl-images-amazon.com/images/I/8143FLAy6GL._SL1500_.jpg','$2.89');
INSERT INTO QuestProducts VALUES (23, 'Yellow Onion, One Large','AmazonFresh guarantees every product will be delivered to your home well within the manufacturers recommended use by, sell by, best by or expiration date.','https://images-na.ssl-images-amazon.com/images/I/71785Jrt80L._SL1483_.jpg','$0.81');
INSERT INTO QuestProducts VALUES (24, 'Fresh Atlantic Salmon, 12 oz','Marine Harvest Atlantic Salmon is fresh and never frozen; try it baked, broiled, pan-fried, or grilled. Two servings per package; each 6 oz. portion contains 35 grams of protein and 100% of the recommended daily value of Vitamin D. ','https://images-na.ssl-images-amazon.com/images/I/61ChHUPtpSL._SY550_.jpg','$7.49');
INSERT INTO QuestProducts VALUES (25, 'Cucumber, Medium','AmazonFresh guarantees every product will be delivered to your home well within the manufacturers recommended use by, sell by, best by or expiration date.','https://images-na.ssl-images-amazon.com/images/I/71t9Hf2OZ0L._SL1500_.jpg','$0.77');
INSERT INTO QuestProducts VALUES (26, 'Hand-Trimmed Boneless, Skinless Chicken Thighs, 1.25 lb','No added hormones. No antibiotics - ever! Third-party animal humane certified. Born, raised, and harvested in United States.','https://images-na.ssl-images-amazon.com/images/I/71fNVf0v7XL._SY355_.jpg','$5.29');
INSERT INTO QuestProducts VALUES (27, 'Smokehouse Bacon, 12 oz','Vegetarian fed pork. Raised without antibiotics. Brought to you by Whole Foods Market.','https://images-na.ssl-images-amazon.com/images/I/51E2FAGf7KL._SX355_.jpg','$5.99');
INSERT INTO QuestProducts VALUES (28, 'Organic Whole Milk, 128 oz','Brought to you by Whole Foods Market.','https://images-na.ssl-images-amazon.com/images/I/511YqwgiqAL._SY606_.jpg','$5.49');
INSERT INTO QuestProducts VALUES (29, '2% reduced fat chocolate milk, 52 fl oz ','Fairlife Milk 2% Chocolate, 52 oz.','https://images-na.ssl-images-amazon.com/images/I/7173165oQfL._SY355_.jpg','$3.99');
INSERT INTO QuestProducts VALUES (30, 'Almond Breeze, Unsweetened Vanilla, Half Gallon, 64 oz','AmazonFresh guarantees every product will be delivered to your home well within the manufacturers recommended use by, sell by, best by or expiration date.','https://images-na.ssl-images-amazon.com/images/I/41YOKhMdaML.jpg','$2.99');
INSERT INTO QuestProducts VALUES (31, 'Quilted Northern Ultra Soft and Strong Toilet Paper','12 pack double rolls with 176 sheets in every roll = case of 24 regular rolls. 2-ply toilet tissue with Cleanstretch to limit bath tissue ripping and separation.','https://images-na.ssl-images-amazon.com/images/I/81SFcqj07fL._SL1500_.jpg','$6.99');
INSERT INTO QuestProducts VALUES (32, 'Duracell Alkaline 9V Battery ','Battery. Bulk Packaging.','https://images-na.ssl-images-amazon.com/images/I/71oFOpFwoOL._SX355SX355_SY310_CR,0,0,355,310_PIbundle-2,TopRight,0,0_SX355_SY310_CR,0,0,355,310_SH20_.jpg','$6.15');
INSERT INTO QuestProducts VALUES (33, 'Bounty Select-a-Size Paper Towels, White','2X more absorbent,* so you can use less (*Vs. the Custom-Size-It® brand in the U.S. and the Premium Green Leaf Towel in Canada.) 12 Huge Rolls = 30 Regular Rolls','https://images-na.ssl-images-amazon.com/images/I/A10xeRw%2BjoL._SL1500_.jpg','$27.94');
INSERT INTO QuestProducts VALUES (34, 'Mrs Meyers Hand Soap','Phthalate, paraben, dea and sulfate free. Plant-derived ingredients.  Lemon Verbena, 12.5 Fluid Ounce (Pack of 3)','https://images-na.ssl-images-amazon.com/images/I/919YVLtjkUL._SL1500_.jpg','$8.95');
INSERT INTO QuestProducts VALUES (35, 'Dial Liquid Hand Soap','9.375 ounce hand soap with moisturizer. Kills 99.9 percent of germs (bacteria encountered in household settings). ,White Tea/Vitamin E, 9.375 Ounce','https://images-na.ssl-images-amazon.com/images/I/41AR8MCuPFL.jpg','$1.86');
INSERT INTO QuestProducts VALUES (36, '12-Piece Stainless Steel Cookware Set','Includes: 1.5 qt saucepan, 1.5, 2, and 3 qt casserole, 5.5 qt stockpot, and a 10 in. fry pan with lids. Made of mirror polished 18/10 stainless steel. Oven safe to 500F, glass lids to 350F. Dishwasher safe. ','https://images-na.ssl-images-amazon.com/images/I/8179-MW30AL._SL1500_.jpg','$51.13');
INSERT INTO QuestProducts VALUES (37, 'Blender Plus 24 oz Smoothie Cup','Dual Direction Blade Technology for extra blending power to chop and grind with precision. Extra wide 3.5” blade system allows ingredients to flow down into the blade easier for faster and smoother results. 1200 power watts and 900 watts of ice crushing power. ','https://images-na.ssl-images-amazon.com/images/I/91xISeCtFXL._SL1500_.jpg','$52.99');
INSERT INTO QuestProducts VALUES (38, 'Crock-Pot / Manual Portable Slow Cooker','Stainless steel 6-quart portable slow cooker, serves 7+ people. Handles make it easy to carry, High/Low/Warm settings. Polished, silver stainless steel exterior with black accents and plastic handles.','https://images-na.ssl-images-amazon.com/images/I/41fqm2pQu%2BL.jpg','$29.50');
INSERT INTO QuestProducts VALUES (39, 'George Foreman Electric Indoor Grill and Panini Press','Fits two servings of your grilled favorites, perfect for small apartments and couples. Tough Nonstick Coating. Dishwasher safe drip tray.','https://images-na.ssl-images-amazon.com/images/I/81RtnK8pjzL._SL1500_.jpg','$18.59');
INSERT INTO QuestProducts VALUES (40, '25-Piece Kitchen Utensil Set','Quality 25 piece kitchen utensils set. Stainless Steel & Nylon.','https://images-na.ssl-images-amazon.com/images/I/71XucRWzZzL._SL1500_.jpg','$24.33');
INSERT INTO QuestProducts VALUES (41, '18-Piece Dinnerware Set, Service for 6','18-piece round dinnerware set; service for 6. AB-grade porcelain; lightweight yet durable. Safe in your microwave, oven, and freezer as well as dishwasher-safe. Includes 6 each: 10.5-inch dinner plate, 7.5-inch dessert plate, 5.5-inch bowl, porcelain,solid white. Plates can withstand a maximum temperature of 572 degrees (Fahrenheit).','https://images-na.ssl-images-amazon.com/images/I/61Rmo6TPAjL._SL1500_.jpg','$31.99');
INSERT INTO QuestProducts VALUES (42, 'Charcoal Grill','Dimensions 17-inch by 17-inch by 23-inch, 18.5 inch diameter of BBQ grill plated steel cooking replaced grate. ','https://images-na.ssl-images-amazon.com/images/I/61HsUOmapNL._SL1000_.jpg','$47.99');
INSERT INTO QuestProducts VALUES (43, 'Char-Broil Burner Cart Liquid Propane Gas Grill','4-Burner, 36,000-BTU Cart-Style Gas Grill with 10,000-BTU Lidded Side Burner.475 square inches of primary cooking on porcelain-coated cast iron grates plus 175 square inches of secondary cooking on porcelain-coated swing-away rack. Stainless steel lid, handle and control panel add style and durability. Electronic ignition.','https://images-na.ssl-images-amazon.com/images/I/814Im3nyRlL._SY355_.jpg','193.03');
INSERT INTO QuestProducts VALUES (44, 'Devoko Patio Porch Furniture Set','This patio furniture set include: 1 tea table and 2 wicker chairs. High quality strong steel frames with beige cushions. ','https://images-na.ssl-images-amazon.com/images/I/61NX-mFzbSL._SL1000_.jpg','$139.99');
INSERT INTO QuestProducts VALUES (45, 'Upholstered Sofa, Black Bonded Leather Match','Covered in black bonded leather (seating area) and bi-cast vinyl/PU/faux leather/leatherette (body). Contemporary/Modern style. Measures: 84.25 x 36 x 36.5H inches; minor leg assembly required.','https://images-na.ssl-images-amazon.com/images/I/712qHTZeB7L._SL1500_.jpg','$449.00');
INSERT INTO QuestProducts VALUES (46, 'Bonded Leather Rocker Recliner Living Room Chair','Plush rocker recliner with overstuffed padded seats back and arms. Dimensions of 42 x 40" x 37". Soft and durable bonded leather upholstery. Easy to assemble - Back rest slides into place.','https://images-na.ssl-images-amazon.com/images/I/81bugFOwI-L._SL1500_.jpg','$199.99');
INSERT INTO QuestProducts VALUES (47, 'Womens Floral Printed Long Sleeve T-Shirt','Material: 90% Polyester, 10% Spandex. Good Elasticity, Soft and Comfortable.','https://images-na.ssl-images-amazon.com/images/I/71cdbKT1MiL._UY445_.jpg','$14.99');
INSERT INTO QuestProducts VALUES (48, 'Mens 100% Cotton Long Sleeve Plaid Dress Shirt','Notice: If it smells, please wash shirt in cold water before you wear it. Some buyers say our shirt size is way off, which confuses us, so we have updated our shirt size measurement. Fashion Plaid and Button-down Design, Fashionable Elegance, Convenient and Practical.','https://images-na.ssl-images-amazon.com/images/I/71yb3Aa2vyL._UX342_.jpg','$19.99');
INSERT INTO QuestProducts VALUES (49, 'Adidas Performance Mens Galaxy Tennis Shoe','Textile and Synthetic. Imported. Rubber sole. Breathable mesh lining. Cloudfoam midsole for step-in comfort and superior cushioning.','https://images-na.ssl-images-amazon.com/images/I/910SiUesEyL._UX500_.jpg','$40.62');
INSERT INTO QuestProducts VALUES (50, 'ASICS Womens Tennis Shoe','Made for play on hard courts. Breathable mesh, textile, and synthetic upper materials. Padded tongue and collar. Comfortable fabric lining. Molded foam footbed. ','https://images-na.ssl-images-amazon.com/images/I/61QZFd4fH9L._UY395_.jpg','$69.90');
INSERT INTO QuestProducts VALUES (51, 'North Face Mens Harway Jacket','100% nylon with durable water-repellent finish. Made in USA or Imported.. Embroidered brand logo on left chest and back right shoulder. Lining and insulation: 100% polyester.','https://images-na.ssl-images-amazon.com/images/I/91d4A%2BoK5xL._UX342_.jpg','$99.00');
